### PR TITLE
Appdata

### PR DESCRIPTION
**Pull request by jsbackus**
Patch to address issue #159. Note: after merge, the antimicro.appdata.xml.in file will need to be updated such that the screenshot URLs refer to the primary repository incase I get the urge to spring-clean.

### CODE REVIEW

**Comment by Ryochan7** [comment]
This is looking fine so far but I can't get Gnome Software to use the appdata file. I have Fedora 21 installed on a VM and I am using gnome-software 3.14.2. The generated antimicro.appdata.xml file is valid according to *appstream-util validate* so that isn't the issue.

**Comment by Ryochan7** [comment]
I have pulled the Appdata commits into the repository. Thank you Jeff for working on this.

**Comment by jsbackus** [comment]
Welcome! Sorry for the delay. Yeah, I'm still on F20, too. Had a spare machine I could throw F21 on. Don't know if you were able to view the entry in gnome-software yet. I had to start gnome-software from the terminal with:
gnome-software --prefer-local

Personally, I think that should be the default behavior, but meh.

**Comment by Ryochan7** [comment]
I am probably doing something wrong but I can't get gnome-software to use the information in the appdata file. One thing that I should mention is that I changed the build system a little bit regarding the generation of the appdata file. AppData generation should probably be optional and it doesn't apply for the Windows version. The way it was set up, antimicro.appdata.xml became a mandatory file for the install step on all platforms and itstool was a mandatory dependency. cmake now has to be passed -DAPPDATA=ON in order for the appdata build step to be available.

**Comment by jsbackus** [comment]
Oops! Yes, my knowledge of cmake is ... dangerous. Thanks for fixing it. :smile:.

Hmm. When I was working (fighting?) with gnome-software, I used a non-Gnome desktop (XFCE, I think), and started gnome-software from the terminal with the --prefer-local option. One thing I did notice is that once you start gnome-software, it stays running - even when you close the window. You might try doing a 'killall gnome-software' before starting it from the terminal. It may be that it is already running when you try to start it...

**Pull request closed without merging**
