### PR TITLE
Minor cmake refactor

### PR DESCRIPTION
**Pull request by EmperorArthur**
Instead of doing different cmake checks for headers and actual source files, do it all at once.
Also prefer QT5 over 4 when available.

### CODE REVIEW

**Comment by Ryochan7** [comment]
Everything looks good. At this point, the only time Qt 4 usage is preferred over Qt 5 is for Ubuntu (mainly due to Unity). I haven't tested later versions of Unity but the version bundled with Trusty has a problem with how Qt creates the tray menu and it was a noted problem with versions of Qt 5. I should get around to testing out Vivid and check if the same problem occurs. If not, the Vivid package can start getting built with Qt 5.

**Comment by Ryochan7** [comment]
The latest Ubuntu Vivid package now has antimicro built with Qt 5 support. A few other changes needed to be made to allow minimize to tray to actually work; the window would constantly pop back up right after minimizing. Although, I would suggest that Unity users disable minimize to tray in the settings anyway since the main application menu will not re-appear in the top bar after restoring the window; this happens when antimicro is built with Qt 4 as well. I have tried what I could to work around that problem but that seems more like a problem with Unity.

**Comment by Ryochan7** [comment]
The Vivid and Wily packages are now using Qt 4 again. The Qt 5 version has some major problems in Wily.

**Comment by EmperorArthur** [comment]
Interesting.  Are those compile time or runtime issues?

The last post I could find about Qt 4 end of life is https://blog.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year/

If they don't decide to extend it again, then QT will stop receiving updates pretty soon.

**Comment by Ryochan7** [comment]
There are runtime problems when running the application in Unity. After running the first run wizard, Unity locked up the X session; although I had something similar happen when running Chrome as well. The main application menu still doesn't work right. Also, the tray menu no longer works after hiding the main window; that problem did not happen under Vivid when antimicro was compiled with Qt 5 support. The Qt 4 version works as expected and the application menu problem does not happen anymore.

For now, continuing to compile the program with Qt 4 will be fine as a workaround. However, considering that the next release of Ubuntu will be an LTS release, I would really hope that issues with Qt 5 and Unity get resolved before Ubuntu 16.04 gets released. Other than Ubuntu, the only other system that antimicro gets compiled with Qt 4 support is for the Debian Wheezy / SteamOS Alchemist packages.

**Comment by Ryochan7** [comment]
I just got back to testing Ubuntu Wily after playing with Manjaro for a bit. The build of VLC that is available for Wily uses Qt 5 and it has similar problems in Unity. If the hide option is used from the tray menu then the main application menu will not work after the application window is shown again. However, the tray menu still works after hiding the main window. I have taken a look at the VLC source code for the Qt frontend so I have a couple of changes that I can try later.

As for the stability issues I mentioned before, the nouveau driver was being used so that might have contributed to problems.

**Comment by Ryochan7** [comment]
I don't know why but using the QSystemTrayIcon::isSystemTrayAvailable method in some contexts causes problems in Unity. With the most recent changes, the tray menu works as expected in Unity when compiling antimicro with Qt 5 again. There doesn't seem to be anything that can be done about the main menu bar issue though.

**Pull request merged**
